project_id = "aszoekuhxvywxlthmivs"

[functions.instagram-osint]
verify_jwt = false

[functions.geopolitical-data]
verify_jwt = false

[functions.social-analyzer]
verify_jwt = false

[functions.facecheck-search]
verify_jwt = false